spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/desafiobackend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.liquibase.enabled=${LIQUIBASE_ENABLED:true}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

security.auth.enabled=${SECURITY_AUTH_ENABLED:false}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/desafio-logap}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/desafio-logap/protocol/openid-connect/certs}

management.endpoints.web.exposure.include=health,info
java.runtime.version=11
server.port=${PORT:8080}
